<?php

use App\Models\Country;
use Illuminate\Database\Seeder;

class CountryTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Country::truncate();

        Country::create(['name' => 'Abkhazia', 'phone_code' => 7]);
        Country::create(['name' => 'Afghanistan', 'phone_code' => 93]);
        Country::create(['name' => 'Ajaria', 'phone_code' => 995]);
        Country::create(['name' => 'Akrotiri and Dhekelia', 'phone_code' => 357]);
        Country::create(['name' => 'Albania', 'phone_code' => 355]);
        Country::create(['name' => 'Algeria', 'phone_code' => 213]);
        Country::create(['name' => 'American Samoa', 'phone_code' => 1684]);
        Country::create(['name' => 'Andorra', 'phone_code' => 376]);
        Country::create(['name' => 'Angola', 'phone_code' => 244]);
        Country::create(['name' => 'Anguilla', 'phone_code' => 1264]);
        Country::create(['name' => 'Antigua and Barbuda', 'phone_code' => 1268]);
        Country::create(['name' => 'Argentina', 'phone_code' => 54]);
        Country::create(['name' => 'Armenia', 'phone_code' => 374]);
        Country::create(['name' => 'Aruba', 'phone_code' => 297]);
        Country::create(['name' => 'Australia', 'phone_code' => 61]);
        Country::create(['name' => 'Austria', 'phone_code' => 43]);
        Country::create(['name' => 'Azerbaijan', 'phone_code' => 994]);
        Country::create(['name' => 'Bahamas','phone_code' => 1242]);
        Country::create(['name' => 'Bahrain', 'phone_code' => 973]);
        Country::create(['name' => 'Bangladesh', 'phone_code' => 880]);
        Country::create(['name' => 'Barbados', 'phone_code' => 1246]);
        Country::create(['name' => 'Belarus', 'phone_code' => 375]);
        Country::create(['name' => 'Belgium', 'phone_code' => 32]);
        Country::create(['name' => 'Belize', 'phone_code' => 501]);
        Country::create(['name' => 'Benin', 'phone_code' => 229]);
        Country::create(['name' => 'Bermuda', 'phone_code' => 1441]);
        Country::create(['name' => 'Bhutan', 'phone_code' => 975]);
        Country::create(['name' => 'Bolivia', 'phone_code' => 591]);
        Country::create(['name' => 'Bosnia and Herzegovina', 'phone_code' => 387]);
        Country::create(['name' => 'Botswana', 'phone_code' => 267]);
        Country::create(['name' => 'Brazil', 'phone_code' => 55]);
        Country::create(['name' => 'British Antarctic Territory', 'phone_code' => 0]);
        Country::create(['name' => 'British Indian Ocean Territory', 'phone_code' => 246]);
        Country::create(['name' => 'British Virgin Islands', 'phone_code' => 1284]);
        Country::create(['name' => 'Brunei', 'phone_code' => 673]);
        Country::create(['name' => 'Bulgaria', 'phone_code' => 359]);
        Country::create(['name' => 'Burkina Faso', 'phone_code' => 226]);
        Country::create(['name' => 'Burma', 'phone_code' => 95]);
        Country::create(['name' => 'Burundi', 'phone_code' => 257]);
        Country::create(['name' => 'Cambodia', 'phone_code' => 855]);
        Country::create(['name' => 'Cameroon', 'phone_code' => 237]);
        Country::create(['name' => 'Canada', 'phone_code' => 1]);
        Country::create(['name' => 'Cape Verde', 'phone_code' => 238]);
        Country::create(['name' => 'Cayman Islands', 'phone_code' => 1345]);
        Country::create(['name' => 'Central African Republic', 'phone_code' => 236]);
        Country::create(['name' => 'Chad', 'phone_code' => 235]);
        Country::create(['name' => 'Chile', 'phone_code' => 56]);
        Country::create(['name' => 'China', 'phone_code' => 86]);
        Country::create(['name' => 'Christmas Island', 'phone_code' => 61]);
        Country::create(['name' => 'Cocos (Keeling) Islands', 'phone_code' => 61]);
        Country::create(['name' => 'Colombia', 'phone_code' => 57]);
        Country::create(['name' => 'Comoros', 'phone_code' => 269]);
        Country::create(['name' => 'Congo-Brazzaville', 'phone_code' => 242]);
        Country::create(['name' => 'Congo-Kinshasa', 'phone_code' => 243]);
        Country::create(['name' => 'Cook Islands', 'phone_code' => 682]);
        Country::create(['name' => 'Costa Rica', 'phone_code' => 506]);
        Country::create(['name' => "Cote d'Ivoire", 'phone_code' => 225]);
        Country::create(['name' => 'Crimea', 'phone_code' => 380]);
        Country::create(['name' => 'Croatia', 'phone_code' => 385]);
        Country::create(['name' => 'Cuba', 'phone_code' => 53]);
        Country::create(['name' => 'Cyprus', 'phone_code' => 357]);
        Country::create(['name' => 'Czech Republic', 'phone_code' => 420]);
        Country::create(['name' => 'Denmark', 'phone_code' => 45]);
        Country::create(['name' => 'Djibouti', 'phone_code' => 253]);
        Country::create(['name' => 'Dominica', 'phone_code' => 1767]);
        Country::create(['name' => 'Dominican Republic', 'phone_code' => 1809]);
        Country::create(['name' => 'East Timor', 'phone_code' => 670]);
        Country::create(['name' => 'Ecuador', 'phone_code' => 593]);
        Country::create(['name' => 'Egypt', 'phone_code' => 20]);
        Country::create(['name' => 'El Salvador', 'phone_code' => 503]);
        Country::create(['name' => 'Equatorial Guinea', 'phone_code' => 240]);
        Country::create(['name' => 'Eritrea', 'phone_code' => 291]);
        Country::create(['name' => 'Estonia', 'phone_code' => 372]);
        Country::create(['name' => 'Ethiopia', 'phone_code' => 251]);
        Country::create(['name' => 'Falkland Islands', 'phone_code' => 500]);
        Country::create(['name' => 'Faroe Islands', 'phone_code' => 298]);
        Country::create(['name' => 'Federated States of Micronesia', 'phone_code' => 691]);
        Country::create(['name' => 'Fiji', 'phone_code' => 679]);
        Country::create(['name' => 'Finland', 'phone_code' => 358]);
        Country::create(['name' => 'France', 'phone_code' => 33]);
        Country::create(['name' => 'French Southern and Antarctic Lands', 'phone_code' => 262]);
        Country::create(['name' => 'Gabon', 'phone_code' => 241]);
        Country::create(['name' => 'Gambia', 'phone_code' => 220]);
        Country::create(['name' => 'Georgia', 'phone_code' => 995]);
        Country::create(['name' => 'Germany', 'phone_code' => 49]);
        Country::create(['name' => 'Ghana', 'phone_code' => 233]);
        Country::create(['name' => 'Gibraltar', 'phone_code' => 350]);
        Country::create(['name' => 'Greece', 'phone_code' => 30]);
        Country::create(['name' => 'Greenland', 'phone_code' => 299]);
        Country::create(['name' => 'Grenada', 'phone_code' => 1473]);
        Country::create(['name' => 'Guam', 'phone_code' => 1671]);
        Country::create(['name' => 'Guatemala', 'phone_code' => 502]);
        Country::create(['name' => 'Guinea', 'phone_code' => 224]);
        Country::create(['name' => 'Guinea-Bissau', 'phone_code' => 245]);
        Country::create(['name' => 'Guyana', 'phone_code' => 592]);
        Country::create(['name' => 'Haiti', 'phone_code' => 509]);
        Country::create(['name' => 'Honduras', 'phone_code' => 504]);
        Country::create(['name' => 'Hong Kong', 'phone_code' => 852]);
        Country::create(['name' => 'Hungary', 'phone_code' => 36]);
        Country::create(['name' => 'Iceland', 'phone_code' => 354]);
        Country::create(['name' => 'India', 'phone_code' => 91]);
        Country::create(['name' => 'Indonesia', 'phone_code' => 62]);
        Country::create(['name' => 'Iran', 'phone_code' => 98]);
        Country::create(['name' => 'Iraq', 'phone_code' => 964]);
        Country::create(['name' => 'Ireland', 'phone_code' => 353]);
        Country::create(['name' => 'Israel', 'phone_code' => 972]);
        Country::create(['name' => 'Italy', 'phone_code' => 39]);
        Country::create(['name' => 'Jamaica', 'phone_code' => 1876]);
        Country::create(['name' => 'Japan', 'phone_code' => 81]);
        Country::create(['name' => 'Jordan', 'phone_code' => 962]);
        Country::create(['name' => 'Karakalpakstan', 'phone_code' => 998]);
        Country::create(['name' => 'Kazakhstan', 'phone_code' => 7]);
        Country::create(['name' => 'Kenya', 'phone_code' => 254]);
        Country::create(['name' => 'Kiribati', 'phone_code' => 686]);
        Country::create(['name' => 'Kosovo', 'phone_code' => 381]);
        Country::create(['name' => 'Kuwait', 'phone_code' => 965]);
        Country::create(['name' => 'Kyrgyzstan', 'phone_code' => 996]);
        Country::create(['name' => 'Laos', 'phone_code' => 856]);
        Country::create(['name' => 'Latvia', 'phone_code' => 371]);
        Country::create(['name' => 'Lebanon', 'phone_code' => 961]);
        Country::create(['name' => 'Lesotho', 'phone_code' => 266]);
        Country::create(['name' => 'Liberia', 'phone_code' => 231]);
        Country::create(['name' => 'Libya', 'phone_code' => 218]);
        Country::create(['name' => 'Liechtenstein', 'phone_code' => 423]);
        Country::create(['name' => 'Lithuania', 'phone_code' => 370]);
        Country::create(['name' => 'Luxembourg', 'phone_code' => 352]);
        Country::create(['name' => 'Macau', 'phone_code' => 853]);
        Country::create(['name' => 'Macedonia', 'phone_code' => 389]);
        Country::create(['name' => 'Madagascar', 'phone_code' => 261]);
        Country::create(['name' => 'Malawi', 'phone_code' => 265]);
        Country::create(['name' => 'Malaysia', 'phone_code' => 60]);
        Country::create(['name' => 'Maldives', 'phone_code' => 960]);
        Country::create(['name' => 'Mali', 'phone_code' => 223]);
        Country::create(['name' => 'Malta', 'phone_code' => 356]);
        Country::create(['name' => 'Marshall Islands', 'phone_code' => 692]);
        Country::create(['name' => 'Mauritania', 'phone_code' => 222]);
        Country::create(['name' => 'Mauritius', 'phone_code' => 230]);
        Country::create(['name' => 'Mayotte', 'phone_code' => 262]);
        Country::create(['name' => 'Mexico', 'phone_code' => 52]);
        Country::create(['name' => 'Moldova', 'phone_code' => 373]);
        Country::create(['name' => 'Monaco', 'phone_code' => 377]);
        Country::create(['name' => 'Mongolia', 'phone_code' => 976]);
        Country::create(['name' => 'Montenegro', 'phone_code' => 382]);
        Country::create(['name' => 'Montserrat', 'phone_code' => 1664]);
        Country::create(['name' => 'Morocco', 'phone_code' => 212]);
        Country::create(['name' => 'Mozambique', 'phone_code' => 258]);
        Country::create(['name' => 'Nagorno-Karabakh Republic', 'phone_code' => 374]);
        Country::create(['name' => 'Namibia', 'phone_code' => 264]);
        Country::create(['name' => 'Nauru', 'phone_code' => 674]);
        Country::create(['name' => 'Nepal', 'phone_code' => 977]);
        Country::create(['name' => 'Netherlands', 'phone_code' => 31]);
        Country::create(['name' => 'Netherlands Antilles', 'phone_code' => 599]);
        Country::create(['name' => 'New Caledonia', 'phone_code' => 687]);
        Country::create(['name' => 'New Zealand', 'phone_code' => 64]);
        Country::create(['name' => 'Nicaragua', 'phone_code' => 505]);
        Country::create(['name' => 'Niger', 'phone_code' => 227]);
        Country::create(['name' => 'Nigeria', 'phone_code' => 234]);
        Country::create(['name' => 'Niue', 'phone_code' => 683]);
        Country::create(['name' => 'Norfolk Island', 'phone_code' => 672]);
        Country::create(['name' => 'North Korea', 'phone_code' => 850]);
        Country::create(['name' => 'Northern Cyprus', 'phone_code' => 90392]);
        Country::create(['name' => 'Northern Mariana Islands', 'phone_code' => 1670]);
        Country::create(['name' => 'Norway', 'phone_code' => 47]);
        Country::create(['name' => 'Oman', 'phone_code' => 968]);
        Country::create(['name' => 'Pakistan', 'phone_code' => 92]);
        Country::create(['name' => 'Palau', 'phone_code' => 680]);
        Country::create(['name' => 'Palestine', 'phone_code' => 970]);
        Country::create(['name' => 'Panama', 'phone_code' => 507]);
        Country::create(['name' => 'Papua New Guinea', 'phone_code' => 675]);
        Country::create(['name' => 'Paraguay', 'phone_code' => 595]);
        Country::create(['name' => 'Peru', 'phone_code' => 51]);
        Country::create(['name' => 'Philippines', 'phone_code' => 63]);
        Country::create(['name' => 'Pitcairn Islands', 'phone_code' => 870]);
        Country::create(['name' => 'Poland', 'phone_code' => 48]);
        Country::create(['name' => 'Polynesia', 'phone_code' => 689]);
        Country::create(['name' => 'Portugal', 'phone_code' => 351]);
        Country::create(['name' => 'Puerto Rico', 'phone_code' => 1]);
        Country::create(['name' => 'Qatar', 'phone_code' => 974]);
        Country::create(['name' => 'Romania', 'phone_code' => 40]);
        Country::create(['name' => 'Russia', 'phone_code' => 7]);
        Country::create(['name' => 'Rwanda', 'phone_code' => 250]);
        Country::create(['name' => 'Saint Barthelemy', 'phone_code' => 590]);
        Country::create(['name' => 'Saint Helena', 'phone_code' => 290]);
        Country::create(['name' => 'Saint Kitts and Nevis', 'phone_code' => 1869]);
        Country::create(['name' => 'Saint Lucia', 'phone_code' => 1758]);
        Country::create(['name' => 'Saint Martin', 'phone_code' => 1599]);
        Country::create(['name' => 'Saint Pierre and Miquelon', 'phone_code' => 508]);
        Country::create(['name' => 'Saint Vincent and the Grenadines', 'phone_code' => 1784]);
        Country::create(['name' => 'Samoa', 'phone_code' => 685]);
        Country::create(['name' => 'San Marino', 'phone_code' => 378]);
        Country::create(['name' => 'Sao Tome and Principe', 'phone_code' => 239]);
        Country::create(['name' => 'Saudi Arabia', 'phone_code' => 966]);
        Country::create(['name' => 'Senegal', 'phone_code' => 221]);
        Country::create(['name' => 'Serbia', 'phone_code' => 381]);
        Country::create(['name' => 'Seychelles', 'phone_code' => 248]);
        Country::create(['name' => 'Sierra Leone', 'phone_code' => 232]);
        Country::create(['name' => 'Singapore', 'phone_code' => 65]);
        Country::create(['name' => 'Slovakia', 'phone_code' => 421]);
        Country::create(['name' => 'Slovenia', 'phone_code' => 386]);
        Country::create(['name' => 'Solomon Islands', 'phone_code' => 677]);
        Country::create(['name' => 'Somalia', 'phone_code' => 252]);
        Country::create(['name' => 'Somaliland', 'phone_code' => 252]);
        Country::create(['name' => 'South Africa', 'phone_code' => 27]);
        Country::create(['name' => 'South Georgia and the South Sandwich Islands', 'phone_code' => 500]);
        Country::create(['name' => 'South Korea', 'phone_code' => 82]);
        Country::create(['name' => 'South Ossetia', 'phone_code' => 99534]);
        Country::create(['name' => 'Spain', 'phone_code' => 34]);
        Country::create(['name' => 'Sri Lanka', 'phone_code' => 94]);
        Country::create(['name' => 'Sudan', 'phone_code' => 249]);
        Country::create(['name' => 'Suriname', 'phone_code' => 597]);
        Country::create(['name' => 'Swaziland', 'phone_code' => 268]);
        Country::create(['name' => 'Sweden', 'phone_code' => 46]);
        Country::create(['name' => 'Switzerland', 'phone_code' => 41]);
        Country::create(['name' => 'Syria', 'phone_code' => 963]);
        Country::create(['name' => 'Taiwan', 'phone_code' => 886]);
        Country::create(['name' => 'Tajikistan', 'phone_code' => 992]);
        Country::create(['name' => 'Tanzania', 'phone_code' => 255]);
        Country::create(['name' => 'Thailand', 'phone_code' => 66]);
        Country::create(['name' => 'Togo', 'phone_code' => 228]);
        Country::create(['name' => 'Tokelau', 'phone_code' => 690]);
        Country::create(['name' => 'Tonga', 'phone_code' => 676]);
        Country::create(['name' => 'Transnistria', 'phone_code' => 373]);
        Country::create(['name' => 'Trinidad and Tobago', 'phone_code' => 1868]);
        Country::create(['name' => 'Tunisia', 'phone_code' => 216]);
        Country::create(['name' => 'Turkey', 'phone_code' => 90]);
        Country::create(['name' => 'Turkmenistan', 'phone_code' => 993]);
        Country::create(['name' => 'Turks and Caicos Islands', 'phone_code' => 1649]);
        Country::create(['name' => 'Tuvalu', 'phone_code' => 688]);
        Country::create(['name' => 'Uganda', 'phone_code' => 256]);
        Country::create(['name' => 'Ukraine', 'phone_code' => 380]);
        Country::create(['name' => 'United Arab Emirates', 'phone_code' => 971]);
        Country::create(['name' => 'United Kingdom', 'phone_code' => 44]);
        Country::create(['name' => 'United States', 'phone_code' => 1]);
        Country::create(['name' => 'United States Virgin Islands', 'phone_code' => 1340]);
        Country::create(['name' => 'Uruguay', 'phone_code' => 598]);
        Country::create(['name' => 'Uzbekistan', 'phone_code' => 998]);
        Country::create(['name' => 'Vanuatu', 'phone_code' => 678]);
        Country::create(['name' => 'Vatican City', 'phone_code' => 379]);
        Country::create(['name' => 'Venezuela', 'phone_code' => 58]);
        Country::create(['name' => 'Vietnam', 'phone_code' => 84]);
        Country::create(['name' => 'Wallis and Futuna', 'phone_code' => 681]);
        Country::create(['name' => 'Western Sahara', 'phone_code' => 212]);
        Country::create(['name' => 'Yemen', 'phone_code' => 967]);
        Country::create(['name' => 'Zambia', 'phone_code' => 260]);
        Country::create(['name' => 'Zimbabwe', 'phone_code' => 263]);
    }
}
